services:
  - type: web
    name: movie-recommendation-system
    runtime: python

    
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn --workers 1 --timeout 60 app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
